language: python
dist: xenial
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database asgard;' -U postgres
install:
  - pip install pipenv
  - pipenv install --system --deploy --ignore-pipfile --dev
script:
  - pipenv run py.test -v --cov=hollowman --cov=asgard --cov-report term-missing -v itests/
  - pipenv run py.test -v --cov=hollowman --cov=asgard --cov-report term-missing -v tests/
after_success:
  - codecov
