image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          - pip --version
          - pip install -r requirements-tests.txt
          - py.test -v --cov
