version: 2.1

commands:
  fmt-check:
    description: "Confirma que a formatação do código"
    steps:
      - run: "pipenv run fmt-check"
  lint:
    description: "Confirma que a tipagem do código está correta"
    steps:
      - run: "pipenv run lint"
  isort-check:
    description: "Confirma que a ordem dos imports está correta"
    steps:
      - run: "pipenv run isort-check"
  typehint-cov:
    description: "Upload de coverage de typehint"
    steps:
      - run:
          name: "Typehint coverage report"
          command: |
            mkdir -p .mypy/xml/cov
            pipenv run lint --cobertura-xml-report .mypy/xml/cov
            pipenv run codecov --flags typehint --file .mypy/xml/cov/cobertura.xml
            rm -rf .mypy/
  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run all-tests"

jobs:
  py368: &template
    docker:
      - image: circleci/python:3.6.8
        environment:
          TEST_DB_URL: "postgresql://postgres@127.0.0.1/asgard"
          TEST_STATS_API_URL: "http://127.0.0.1:9200"
      - image: postgres:9.4
      - image: elasticsearch:5.5-alpine
    steps:
      - checkout
      - run: sudo apt-get install postgresql-client
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==18.0 pipenv==2018.7.1
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install asgard-api dev-mode
          command: pipenv run pip install -e .
      - run: psql -c 'create database asgard;' -U postgres -p 5432 -h localhost
      - fmt-check
      - isort-check
      - lint
      - all-tests
      - run:
          when: on_success
          command: pipenv run codecov --flags unittest
  py37x:
      <<: *template
      docker:
        - image: circleci/python:3.7
          environment:
            TEST_DB_URL: "postgresql://postgres@127.0.0.1/asgard"
            TEST_STATS_API_URL: "http://127.0.0.1:9200"
        - image: postgres:9.4
        - image: elasticsearch:5.5-alpine
  py36x:
      <<: *template
      docker:
        - image: circleci/python:3.6
          environment:
            TEST_DB_URL: "postgresql://postgres@127.0.0.1/asgard"
            TEST_STATS_API_URL: "http://127.0.0.1:9200"
        - image: postgres:9.4
        - image: elasticsearch:5.5-alpine
workflows:
  version: 2
  required-checks:
    jobs:
      - py368
      - py36x
  optional-checks:
    jobs:
      - py37x
