version: 2.1

commands:
  fmt-check:
    description: "Confirma que a formatação do código"
    steps:
      - run: "pipenv run fmt-check"
  lint:
    description: "Confirma que a tipagem do código está correta"
    steps:
      - run: "pipenv run lint"
  isort-check:
    description: "Confirma que a ordem dos imports está correta"
    steps:
      - run: "pipenv run isort-check"
  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run all-tests"

jobs:
  py368: &template
    docker:
      - image: circleci/python:3.6.8
      - image: postgres:9.4
    steps:
      - checkout
      - run: sudo apt-get install postgresql-client
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==18.0 pipenv==2018.7.1
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install asgard-api dev-mode
          command: pipenv run pip install -e .
      - run: psql -c 'create database asgard;' -U postgres -p 5432 -h localhost
      - fmt-check
      - isort-check
      - lint
      - all-tests
      - run:
          when: on_success
          command: pipenv run codecov
  py37x:
      <<: *template
      docker:
        - image: circleci/python:3.7
        - image: postgres:9.4
  py36x:
      <<: *template
      docker:
        - image: circleci/python:3.6
        - image: postgres:9.4
workflows:
  version: 2
  required-checks:
    jobs:
      - py368
      - py36x
  optional-checks:
    jobs:
      - py37x
