version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

commands:
  fmt-check:
    description: "Confirma que a formatação do código está correta"
    steps:
      - run: "pipenv run fmt-check"
  lint:
    description: "Confirma que a tipagem do código está correta"
    steps:
      - run: "pipenv run lint"
  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run all-tests"

jobs:
  test:
    docker:
      - image: circleci/python:3.6
      - image: rabbitmq:3.7-alpine
    steps:
      - checkout
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==18.0 pipenv==2018.7.1
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install asgard-api dev-mode
          command: pipenv run pip install -e .
      - fmt-check
      - lint
      - all-tests
workflows:
  version: 2
  test:
    jobs:
      - test
